// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-7qlfAntwaEYaTx71D8NVX4Rg7PsjUE',
    appId: '1:113934053927:web:9acde5b18cf70e87569402',
    messagingSenderId: '113934053927',
    projectId: 'project-form-app-test',
    authDomain: 'project-form-app-test.firebaseapp.com',
    storageBucket: 'project-form-app-test.appspot.com',
    measurementId: 'G-TGD6TTP52R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjNlCM_1dw9EzIhWu-uprMSHY6tJcvryA',
    appId: '1:113934053927:android:dc2d4e799bf6077f569402',
    messagingSenderId: '113934053927',
    projectId: 'project-form-app-test',
    storageBucket: 'project-form-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdSgZnxxnI6xMK2leU1GvKq0BdOwZckzg',
    appId: '1:113934053927:ios:7f5481bdfe34c9d3569402',
    messagingSenderId: '113934053927',
    projectId: 'project-form-app-test',
    storageBucket: 'project-form-app-test.appspot.com',
    iosBundleId: 'com.example.partLogin1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdSgZnxxnI6xMK2leU1GvKq0BdOwZckzg',
    appId: '1:113934053927:ios:7f5481bdfe34c9d3569402',
    messagingSenderId: '113934053927',
    projectId: 'project-form-app-test',
    storageBucket: 'project-form-app-test.appspot.com',
    iosBundleId: 'com.example.partLogin1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9-7qlfAntwaEYaTx71D8NVX4Rg7PsjUE',
    appId: '1:113934053927:web:98ac849b4688df44569402',
    messagingSenderId: '113934053927',
    projectId: 'project-form-app-test',
    authDomain: 'project-form-app-test.firebaseapp.com',
    storageBucket: 'project-form-app-test.appspot.com',
    measurementId: 'G-4EK8TVNZNX',
  );
}
